# Generated by Django 3.1.4 on 2020-12-13 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=264, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.CharField(max_length=264, unique=True)),
                ('max_price', models.CharField(max_length=264, unique=True)),
                ('min_price', models.CharField(max_length=264, unique=True)),
                ('stock_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.stock')),
            ],
        ),
        migrations.CreateModel(
            name='DateRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('stock_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.stock')),
            ],
        ),
    ]
