# Generated by Django 3.1.4 on 2020-12-16 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=264, unique=True)),
                ('stock_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.stock')),
            ],
        ),
    ]
